function stats = misstdoa_briefer_report(sol)
% MISSTDOA_BRIEFER_REPORT Print status report for current solution

[zcalc,zok] = misstdoa_calc_z(sol);
zerr = zcalc(:)-sol.z(:);
zinl = sol.inlmatrix(:);
zerr = zerr(find(zinl));
disp(['R:' num2str(length(sol.rows)) '/' num2str(size(sol.z,1)) ...
    ' C:' num2str(length(sol.cols)) '/' num2str(size(sol.z,2)) ...
    ' I:' num2str(sum(sol.inlmatrix(:))) '/' num2str(prod(size(sol.z))) ...
    ' P:' num2str(sum(zok(:))) '/' num2str(prod(size(sol.z)))  ...
    ' E: ' num2str(std(zerr))]);
stats = [...
length(sol.rows) size(sol.z,1); ...
length(sol.cols) size(sol.z,2); ...
sum(sol.inlmatrix(:)) prod(size(sol.z)); ...
sum(zok(:)) prod(size(sol.z)); ...
std(zerr) 0];

